# Linter Options
options:
  merge-default-rules: false
  formatter: stylish
# File Options
files:
  include: '**/*.scss'
  ignore:
    - '**/_normalize.scss'
    - '**/_reset.scss'
    - '**/_margin.scss'
    - '**/_padding.scss'
    - '**/_template.scss'
# Rule Configuration
rules:
  indentation:
    - 1
    -
      size: 2
  no-important: 0
  space-after-colon:
    - 1
    -
      include: true
  space-before-bang:
    - 1
    -
      include: true
  space-before-brace:
    - 1
    -
      include: true
  trailing-semicolon:
    - 2
    -
      include: true
  zero-unit:
    - 1
    -
      include: false
